//This module is included in
//
<<<<<<< HEAD
// * assembly_installing-che-using-the-che-operator-in-openshift-4-web-console
=======
// assembly_installing-che-on-openshift-4-using-operatorhub
>>>>>>> dd259840 (Update Installing Che on OpenShift 4)

[id="installing-the-che-operator_{context}"]
= Installing the {prod} Operator

<<<<<<< HEAD
{prod} Operator provides all the resources for running {prod-short}, such as PostgreSQL, {identity-provider}, image registries, and the {prod-short} server, and also configures all these services.

.Prerequisites

* Access to the Web Console on the cluster.

.Procedure

. To install the {prod} Operator, in the left panel, navigate to the *Operators* -> *OperatorHub* section.

. In the *Filter by keyword* field, type `{prod}` and click the *{prod}* tile.

. In the *{prod}* pop-up window, click the btn:[Install] button.

. On the *Install Operator* screen, specify the following options:
+
* *Installation mode*: *A specific {orch-namespace} on the cluster*
* *Installed Namespace*: *Pick an existing {orch-namespace} -> `{prod-namespace}`

.Verification steps

. To verify the {prod} Operator has installed correctly, in the left panel navigate to the *Operators* -> *Installed Operators* section.

. In the *Installed Operators* screen, click the *{prod}* name and navigate to the *Details* tab.

. In the *ClusterServiceVersion Details* section at the bottom of the page, wait for these messages:
+
* *Status*: `Succeeded`
* *Status Reason*: `install strategy completed with no errors`

. Navigate to the *Events* tab and wait for this message: `install strategy completed with no errors`.
=======
{prod} Operator provides all the resources for running {prod-short}, such as PostgreSQL, {identity-provider}, image registries, and the {prod-short} server, and it also configures all these services.

.Prerequisites

* Access to the OpenShift web console on the cluster. 

.Procedure

. In the left panel, navigate to the *Operators* -> *OperatorHub* page.

. In the *Filter by keyword* field, enter `{prod}`. 

. Click the *{prod}* tile.

. In the *{prod}* pop-up window, click the btn:[Install] button.

. On the *Install Operator* page, click the btn:[Install] button.

.Verification steps

. To verify that the {prod} Operator has installed correctly, in the left panel, navigate to the *Operators* -> *Installed Operators* page.

. On the *Installed Operators* page, click the *{prod}* name and navigate to the *Details* tab.

. In the *ClusterServiceVersion details* section, wait for the following messages:
+
* *Status*: `Succeeded`
* *Status reason*: `install strategy completed with no errors`

. Navigate to the *Events* tab and wait for the following message: `install strategy completed with no errors`.
>>>>>>> dd259840 (Update Installing Che on OpenShift 4)
